#!/usr/bin/env node
// gen-tests.js — single source of truth for report/tests.js.
// Run from repo root: node tools/gen-tests.js
//
// Builds the TESTS global (consumed by report/index.html) directly from the
// rubrics/ (criterion ids, weights, canary-adjacent metadata) and tests/
// (category + title). This removes the hand-edited TESTS block that used to
// live inside index.html, so criterion ids/weights/titles can never drift
// from the rubrics — edit a rubric, re-run this, done.
'use strict';
const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..');
const TESTS_OUT = path.join(REPO, 'report', 'tests.js');

// --- category id -> label (only used to sanity-check test dirs) ---
const KNOWN_CATS = new Set(fs.readdirSync(path.join(REPO, 'tests')).filter(d => {
  try { return fs.statSync(path.join(REPO, 'tests', d)).isDirectory(); }
  catch { return false; }
}));

// --- index: test id -> category + title from tests/ ---
const testIndex = {}; // id -> {category, title}
for (const cat of KNOWN_CATS) {
  const dp = path.join(REPO, 'tests', cat);
  for (const f of fs.readdirSync(dp)) {
    if (!f.endsWith('.md')) continue;
    const id = f.replace(/\.md$/, '');
    const txt = fs.readFileSync(path.join(dp, f), 'utf8');
    const title = (txt.match(/^title:\s*(.+)$/m) || [])[1] || id;
    testIndex[id] = { category: cat, title };
  }
}

// --- parse every rubric ---
function parseFrontmatter(txt) {
  const fm = txt.slice(0, txt.indexOf('\n---', 3));
  const get = re => (txt.match(re) || [])[1];
  const test = get(/^test:\s*(.+?)\s*$/m);
  const canary = (get(/^canary:\s*"?(.+?)"?\s*$/m) || '').replace(/^["']|["']$/g, '').trim();
  const wm = txt.match(/^weights:\s*\n\s*objective:\s*([\d.]+)\s*\n\s*subjective:\s*([\d.]+)/m);
  const weights = wm ? { objective: parseFloat(wm[1]), subjective: parseFloat(wm[2]) } : null;
  const aliases = (get(/^canary_aliases:\s*\[(.+?)\]\s*$/m) || '')
    .split(',').map(s => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean);

  const obj = [], sub = [];
  let inObj = false, inSub = false, cur = null;
  for (const line of txt.split('\n')) {
    const t = line.trim();
    if (t === 'objective:') { inObj = true; inSub = false; continue; }
    if (t === 'subjective:') { inSub = true; inObj = false; continue; }
    if (t === '---' && (inObj || inSub)) break;
    if (inObj) {
      const im = line.match(/^\s*-?\s*id:\s*(\S+)/);
      if (im) { cur = { id: im[1], check: im[1] }; obj.push(cur); }
      const cm = line.match(/check:\s*"(.*)"\s*$/);
      if (cm && cur) cur.check = cm[1];
    }
    if (inSub) {
      const im = line.match(/^\s*-?\s*id:\s*(\S+)/);
      if (im) { cur = { id: im[1], name: im[1], w: 0.3 }; sub.push(cur); }
      const nm = line.match(/name:\s*"(.*?)"/);
      if (nm && cur) cur.name = nm[1];
      const wm2 = line.match(/weight:\s*([\d.]+)/);
      if (wm2 && cur) cur.w = parseFloat(wm2[1]);
    }
  }
  return { test, canary, weights, aliases, obj, sub };
}

const entries = {};
for (const f of fs.readdirSync(path.join(REPO, 'rubrics'))) {
  if (!f.endsWith('.md')) continue;
  const txt = fs.readFileSync(path.join(REPO, 'rubrics', f), 'utf8');
  const p = parseFrontmatter(txt);
  if (!p.test) continue;
  const meta = testIndex[p.test] || { category: 'unknown', title: p.test };
  const objective = p.obj.map(o => [o.id, o.check]);
  const subjective = p.sub.map(s => [s.id, s.name, s.w]);
  const entry = { category: meta.category, title: meta.title, objective, subjective };
  if (p.weights) entry.weights = p.weights;
  entries[p.test] = entry;
}

// --- serialize (stable, readable) ---
const ids = Object.keys(entries).sort((a, b) => {
  const ka = a.match(/^([a-z0-9]+)-(\d+)([a-z]?)/), kb = b.match(/^([a-z0-9]+)-(\d+)([a-z]?)/);
  const pa = ka ? [ka[1], parseInt(ka[2], 10), ka[3] || ''] : [a, 0, ''];
  const pb = kb ? [kb[1], parseInt(kb[2], 10), kb[3] || ''] : [b, 0, ''];
  if (pa[0] !== pb[0]) return pa[0] < pb[0] ? -1 : 1;
  if (pa[1] !== pb[1]) return pa[1] - pb[1];
  return pa[2] < pb[2] ? -1 : pb[2] < pa[2] ? 1 : 0;
});

let out = '// AUTO-GENERATED by tools/gen-tests.js — do not edit by hand.\n';
out += '// Source of truth: rubrics/ (criterion ids, weights) + tests/ (category, title).\n';
out += 'const TESTS={\n';
for (const id of ids) {
  const e = entries[id];
  const obj = e.objective.map(o => '["' + o[0] + '",' + JSON.stringify(o[1]) + ']').join(',');
  const sub = e.subjective.map(s => '["' + s[0] + '",' + JSON.stringify(s[1]) + ',' + s[2] + ']').join(',');
  const w = e.weights ? ',weights:{objective:' + e.weights.objective + ',subjective:' + e.weights.subjective + '}' : '';
  out += '  ' + JSON.stringify(id) + ':{category:' + JSON.stringify(e.category)
    + ',title:' + JSON.stringify(e.title)
    + ',objective:[' + obj + ']'
    + ',subjective:[' + sub + ']' + w + '},\n';
}
out += '};\n';

fs.writeFileSync(TESTS_OUT, out);
console.log('gen-tests: wrote ' + ids.length + ' TESTS entries to report/tests.js');

if (require.main === module) { /* standalone run */ }
module.exports = { genTests: () => fs.writeFileSync(TESTS_OUT, out), parseFrontmatter };
